name: al
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - astropy
  - scipy
  - scikit-image
  - tqdm
  - loguru
  - pytest
  - pillow
  - dotmap
  - pip
  - pip:
    - setuptools
    - wheel
    - build
