name: fb
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.9
  - astropy>=6.0
  - scipy
  - scikit-image
  - tqdm
  - loguru
  - pytest
  - pillow
  - dotmap
  - pip
  - pip:
    - setuptools
    - wheel
    - build
