name: fb
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.26
  - astropy>=6.0
  - scikit-image
  - tqdm
  - pytest
  - pillow
  - dotmap
  - tifffile
  - pip
  - pip:
    - setuptools
    - wheel
    - build
    - opencv-python-headless>=4.5
